%YAML 1.2
---
common:
    pipeline_version: "v0.1"
    emails: " -c chouh@nih.gov"
    juicer_jar: "/usr/local/apps/juicer/juicer-1.5.6/scripts/juicer_tools.jar"
    FASTQ_suffix_R1: "_R1.fastq.gz"
    FASTQ_suffix_R2: "_R2.fastq.gz"
cluster:
    small: "--partition=quick,norm    --time=03:00:00 --mem=02G  --cpus-per-task=1   --gres=lscratch:02"
    medium: "--partition=ccr,norm    --time=24:00:00 --mem=32G  --cpus-per-task=8  --gres=lscratch:05"
    large: "--partition=ccr,norm    --time=24:00:00 --mem=120G  --cpus-per-task=24  --gres=lscratch:05"    
version:
    hicpro: "2.11.1"
hg19:
    hicpro_config: config/config_hicpro_hg19.txt
    bowtie2_index: "ucsc.hg19"
    fragment_bed: "/data/khanlab/projects/HiC/reference_files/dpnii.ucsc.hg19.bed"
    capture_bed: "virtualHiC_MYOD1gene"
    juicer_genome: "hg19"    
mm10:
    hicpro_config: config/config_hicpro_mm10.txt
    bowtie2_index: genome

