%YAML 1.2
---
common:
    pipeline_version: "v0.1"
    emails: " -c chouh@nih.gov"
    FASTQ_suffix_R1: "_R1.fastq.gz"
    FASTQ_suffix_R2: "_R2.fastq.gz"
    FASTQ_suffix_SE: ".fastq.gz"
    app_home: "/data/khanlab/apps"
cluster:
    small: "--partition=quick,norm    --time=03:00:00 --mem=02G  --cpus-per-task=1   --gres=lscratch:02"
    medium: "--partition=ccr,norm    --time=24:00:00 --mem=32G  --cpus-per-task=8  --gres=lscratch:05"
    large: "--partition=ccr,norm    --time=24:00:00 --mem=120G  --cpus-per-task=24  --gres=lscratch:05"
    job_xenofilter: "--partition=ccr,norm --time=10:00:00 --mem=80G  --cpus-per-task=2  --gres=lscratch:200"
    job_xenome: "--partition=ccr,norm --time=24:00:00 --mem=100G  --cpus-per-task=16  --gres=lscratch:200"
    job_xengsort: "--partition=ccr,norm --time=24:00:00 --mem=80G  --cpus-per-task=30  --gres=lscratch:800"
    job_star: "--partition=ccr,norm --time=30:00:00 --mem=200G  --cpus-per-task=30  --gres=lscratch:800"
    job_rsem: "--partition=ccr,norm --time=10:00:00 --mem=200G  --cpus-per-task=30  --gres=lscratch:400"
    job_seq2hla: "--partition=ccr,norm    --time=24:00:00 --mem=32G  --cpus-per-task=8  --gres=lscratch:05"
    job_hlaminer: "--partition=ccr,norm    --time=24:00:00 --mem=32G  --cpus-per-task=8  --gres=lscratch:05"
version:
    star: "2.5.3a"
    samtools: "0.1.19"
    xenome: "1.0.1"
    R: "3.4"
    python2: "2.7"
    python3: "3.6"
    bowtie: "1.1.1"
    rsem: "1.3.0"
    HLAminer: "1.3.1"
annotations:
    - ens
    - ucsc
hg19:
    star_index_ens: "/data/Clinomics/Ref/khanlab/Index/STAR_ens_hg19"
    star_index_ucsc: "/data/Clinomics/Ref/khanlab/Index/star_ucsc_fusion_index/ref_genome.fa.star.idx"
    rsem_ref_ens: "/data/Clinomics/Ref/khanlab/Index/RSEM_ENS/hg19"
    rsem_ref_ucsc: "/data/Clinomics/Ref/khanlab/Index/RSEM_UCSC/hg19"
    xenome_ref: "/fdb/xenome/idx"
    hla_ref : "/data/Clinomics/Ref/khanlab/HLA/"
    xengsort_ref: "/data/khanlab/ref/xengsort/xengsort-index-k25.hg38.mm10.h5"
mm10:
    star_index_ens: "/fdb/STAR_indices/2.5.3a/GENCODE/Gencode_mouse/release_M16/genes-100/"
    star_index_ucsc: "/fdb/STAR_indices/2.5.2b/UCSC/mm10/genes-100/"
    rsem_ref_ens: "/fdb/rsem/ref_from_genome/mouse_ref_GRCm38.82"
    rsem_ref_ucsc: "/fdb/rsem/ref_from_genome/mm10_VM14"

